### ISSUE TITLE
Can sanefalcon run with bgzip type of .bam file?

### ISSUE THREAD

**Issue by KhanhLPBao** [rstraver/sanefalcon#10]
Hi, I just realized that ./prepSamples.sh can only recognize .bam format. However, my hardware is limited so I cannot afford so much for the uncompressed .bam files (which about 4gb each and I have about 200-300 sample files). Is there anyway for the program to run on the compressed .bam file? Thank you very much

**Comment by rstraver** [comment]
Hi, I was on a break for the past few weeks, hence the delay, sorry about that.

As far as I understand zipping a bam file doesn't really change the data size much so I never looked into that. If you want to, I suppose you could do the following:

1. Change the search query to match your zipped format naming, in this line:
```
for SAMPLE in `find $INDIR -name "*.bam"`
```
2. Inside the for loop underneath, add a line that unpacks the bamfile.
3. Ensure the `$SAMPLE` variable points to this unpacked bamfile.
4. At the end of the loop,  add a line that deletes the unpacked bamfile.

I think retaining the .fwd and .rev files produced should be enough for further analysis, and that way you only have to have an unpacked bam file as long as you work on it.

**Comment by KhanhLPBao** [comment]
> Hi, I was on a break for the past few weeks, hence the delay, sorry about that.
> 
> As far as I understand zipping a bam file doesn't really change the data size much so I never looked into that. If you want to, I suppose you could do the following:
> 
> 1. Change the search query to match your zipped format naming, in this line:
> 
> ```
> for SAMPLE in `find $INDIR -name "*.bam"`
> ```
> 
> 1. Inside the for loop underneath, add a line that unpacks the bamfile.
> 2. Ensure the `$SAMPLE` variable points to this unpacked bamfile.
> 3. At the end of the loop,  add a line that deletes the unpacked bamfile.
> 
> I think retaining the .fwd and .rev files produced should be enough for further analysis, and that way you only have to have an unpacked bam file as long as you work on it.

thank you very much
