### ISSUE TITLE
Some questions about splitting 

### ISSUE THREAD

**Issue by KhanhLPBao** [rstraver/sanefalcon#11]
Hi
I have some question about the training progress:
1 - The training sample on this quote is the samples I made by run ./prepSamples.sh script previously?
>  If you have unlimited amounts of data you may skip this step and simply combine all training data for a single nucleosome track, but that means you can never apply the samples used for training in a later step.

2 - How much .bam samples is enough to bypass splitting step? I'm having about 1000 .bam files but I don't know how much I should apply and how much I should keep for later predicting step if I want to skip the splitting process

3 - If I have to do splitting process, should I make all subsets have the same amount of folder and the number of samples per subfolder. For example each subset has 30 samples and each of them contain 3 folder that stores 3,20,7 samples, respectively.

**Comment by rstraver** [comment]
Hi, it's been a while (5 years) so I hope I remember it right...
1. I think so, yes.
2. I think I used 300-330 samples for my training back then, I figured I needed about 300 samples for nucleosome detection (coverage and catching enough variation wise), hence I had to juggle with my samples to use them for all training steps. If you want to skip this (for now) you could put 300 samples for nucleosome detection, use another 300 for training the predictor after that (don't train the predictor on samples included in the nucleosome track finder), then test with the rest (400) of your samples. As you can see this quickly reduces the data you have left at the end, hence the whole subset crosswise training and testing scheme. I'd be curious to know how well it works if that was applied to a bigger dataset like yours, although I wonder if there's some pitfalls I didn't account for when there's so much more coverage overall.
3. I aimed for roughly equal sets in each subset. I kept batches of samples together (samples ran on the same flow cell) to account for some batch effect possibilities later on. Hence it's not exactly 30 samples per subset, but what was close enough with those constraints.
