### ISSUE TITLE
Preparation of samples

### ISSUE THREAD

**Issue by GreeshmaThulasi** [rstraver/sanefalcon#3]
Hi,
I have around 60 single-end sequenced bam files, which can be used to make reference set. 
I'm sorry that,  I am not clear about your description. Could you please tell the exact code to execute this program.

Thanks in advance.

**Comment by rstraver** [comment]
Hi Greeshma,

I agree the code and way to run everything is not the easiest, and some reimplementation would be nice to streamline things. However, I believe the README contains all information I can provide to help you use SANEFALCON. If you have a more specific question I'll try my best to answer but I cannot tell you how you should run things exactly other than what is already there.

Also, 60 samples might be on the very low end for nucleosome detection, if you I can share a nucleosome track we determined previously and skip that part.

**Comment by GreeshmaThulasi** [comment]
Hi @rstraver ,
Thank you for your quick reply.
I will be glad if you share the nucleosome track file. But is there any platform compatibility matter?(as I am using Ion Torrent test samples).
If you shares, where do I proceed further? Is it from the 'Testing'?

**Comment by rstraver** [comment]
Try this:
https://roystraver.stackstorage.com/s/pSbMYGPJJT1DfZw

That should remove the need for the split training sets and nucleosome track detection. You still need to extract nucleosome start positions and train the nucleosome profile to fetal fraction before you can start calling anything though.

Also I didn't test Ion Torrent myself but considering the method aims to work with read start position rather than anything else, I feel the sequencing platform should not influence results much as the data should be influenced by nucleome positioning. On the other hand, perhaps some areas where normally there are clear nucleome positions are now hardly detectable and the other way around, so it may not be optimal.

**Comment by GreeshmaThulasi** [comment]
Hi,
I downloaded the nucleosome track files.
As you said I can start with extracting nucleosome start positions. Do I have to extract start positions from the nucleosome track file ?
What is this code,
`> python getProfile.py $NUCL.$CHROM $SAMPLE.$CHROM.start.fwd 0 $SAMPLEOUT.$CHROM.fwd
> python getProfile.py $NUCL.$CHROM $SAMPLE.$CHROM.start.fwd 1 $SAMPLEOUT.$CHROM.ifwd
> python getProfile.py $NUCL.$CHROM $SAMPLE.$CHROM.start.rev 1 $SAMPLEOUT.$CHROM.rev
> python getProfile.py $NUCL.$CHROM $SAMPLE.$CHROM.start.rev 0 $SAMPLEOUT.$CHROM.irev` 

meant ? Is the start positions are from forward and reverse reads? My file is single-end sequenced, is that matter?

**Comment by rstraver** [comment]
You need to extract the read start positions from bam files. Forward and reverse are handled seperately. This method was designed for single end sequencing so you should be fine in that respect.
Start with section 2.2 Extracting read start positions, then move on to 3.3.
What that code means is described in 3.3 of the readme.

**Comment by GreeshmaThulasi** [comment]
I extracted read start positions from bam files using the code,
`./prepSamples.sh '/run/user/1000/gvfs/test' '/run/user/1000/gvfs/test' 
`
I got a list of start.fwd and start.rev files, but every files are empty (0KB). I don't know what went wrong.

Sorry for asking frequent doubts.

**Comment by GreeshmaThulasi** [comment]
I think I need to edit the prepSamples.sh file which is, by default written as,
`export DIR_SCRIPTS=/illumina/diagnostics/bin
export SCRIPT_PYTHON=/illumina/diagnostics/bin/Python-2.7.3/bin/python
export SCRIPT_SAMTOOLS=$DIR_SCRIPTS/samtools-0.1.19/samtools`
What are the directories to be exported?

**Comment by rstraver** [comment]
That's just a list of all the tools you aim to use, just replace the paths to match your samtools and python installations.

**Comment by GreeshmaThulasi** [comment]
Thank you.
I extracted the read start positions of each chromosomes(start.fwd and start.rev) for all the samples.
For getting the nucleosome profiles, do I have to repeatedly execute the code 
`
> python getProfile.py $NUCL.$CHROM $SAMPLE.$CHROM.start.fwd 0 $SAMPLEOUT.$CHROM.fwd
> python getProfile.py $NUCL.$CHROM $SAMPLE.$CHROM.start.fwd 1 $SAMPLEOUT.$CHROM.ifwd
> python getProfile.py $NUCL.$CHROM $SAMPLE.$CHROM.start.rev 1 $SAMPLEOUT.$CHROM.rev
> python getProfile.py $NUCL.$CHROM $SAMPLE.$CHROM.start.rev 0 $SAMPLEOUT.$CHROM.irev`

for every 22 chromosomes and for every samples?

**Comment by rstraver** [comment]
Yeah, you can use the $CHROM as a variable in a loop to ease your work on that.

**Comment by GreeshmaThulasi** [comment]
Ok.
I tried. But how to define $CHROM, since there are 22 chromosomes?

**Comment by rstraver** [comment]
Probably with a loop, similar to what is in merge.sh.

**Comment by GreeshmaThulasi** [comment]
Hi,
I executed as,
`ngslab@ngslab-OptiPlex-3050:~/Downloads/sanefalcon-master$ INPUT=/home/ngslab/Downloads/nucl_ex/nucl_ex5.$i`
`ngslab@ngslab-OptiPlex-3050:~/Downloads/sanefalcon-master$ FWD=/run/user/1000/gvfs/smb/test/1/sample1401.bam.$i.start.fwd`
`ngslab@ngslab-OptiPlex-3050:~/Downloads/sanefalcon-master$ OUT=/run/user/1000/gvfs/smb/test/1/2/sample1401.$i.fwd`
`gslab@ngslab-OptiPlex-3050:~/Downloads/sanefalcon-master$ for i in $(seq 1 22); do python getProfile.py $INPUT $FWD 0 $OUT; done`
`161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031
161844 12031

161844 12031`
**But I got only one file that is, sample1401.22.fwd.np** (didn't created files from 1 to 22).
Please help me to resolve this.

**Comment by rstraver** [comment]
You defined your input and output files outside of the loop, I doubt that is going to work.
You may want to read into bash a little bit as these scripts may be hard to work with without some knowledge in that.

**Comment by GreeshmaThulasi** [comment]
Hi,
I resolved the problem. Now I have a set of files as .fwd.np, .ifwd.np, .rev.np and .irev.np (1-22 for all samples).
How to  combine the read start profiles per direction?
In, `./combProf.sh searchDir >> upstreamProfs.csv` **what to give as searchDir**? Is it the whole files .fwd.np, .ifwd.np, .rev.np and .irev.np together or separately?

**Comment by GreeshmaThulasi** [comment]
Hi,
I got 2 files named **upstreamProfs.csv** and **downstreamProfs.csv** for each samples. 
You have mentioned to sort them by filename. Would you please explain how to do ?

**Comment by dprat** [comment]
delete the  first col in both files

then use this command on the upstream file: 
`awk -F "," '{$1=""; print $0}' upstreamProfs.csv | while read -ra words; do for ((i=${#words[@]}-1; i>=0; i--)); do printf "%s " "${words[i]}"; done; echo; done > upstreamProfs1_bis_reverse.csv`

then use the bash command paste to merge the two files and finally re-add the first col containing the samples names in your file : 

`awk -F "," '{print $1}' downstreamProfs1_bis.csv | paste /dev/stdin upstreamProfs1_bis_reverse.csv downstreamProfs_without_first_col.csv > profile_nucleosome1.txt`

(replace the filename with yours)

**Comment by GreeshmaThulasi** [comment]
Hi @dprat,
In the code,
`awk -F "," '{print $1}' downstreamProfs1_bis.csv | paste /dev/stdin upstreamProfs1_bis_reverse.csv downstreamProfs_without_first_col.csv > profile_nucleosome1.txt`
Is **downstreamProfs1_bis.csv** file is the one with the first column(sample name)? and **downstreamProfs_without_first_col.csv** is the one without first column?

**Comment by GreeshmaThulasi** [comment]
I got the nucleosome profile for a sample as (please see the attachment)
[ profile_nucleosome1.txt](https://github.com/VUmcCGP/sanefalcon/files/2075681/profile_nucleosome1.txt)

What should I do next for finding fetal fraction?

**Comment by dprat** [comment]
here put your complete file **upstreamProfs.csv** (with the first col corresponding to the sample name):

`awk -F "," '{$1=""; print $0}' upstreamProfs.csv | while read -ra words; do for ((i=${#words[@]}-1; i>=0; i--)); do printf "%s " "${words[i]}"; done; echo; done > upstreamProfs1_bis_reverse.csv`

the output will correspond to the reverse file without the col corresponding to the samples name

now for the downstream file delete the first col this way:

`awk '{$1=""; print $0}' downstreamProfs.csv > downstreamProfs_without_first_col.csv`

then use this :  
Rq: it's going to take the first col corresponding the samples name, then paste it with the reverse upstream file and the downstream file 

`awk -F "," '{print $1}' downstreamProfs.csv | paste /dev/stdin upstreamProfs1_bis_reverse.csv downstreamProfs_without_first_col.csv > profile_nucleosome1.txt`

in the file **profile_nucleosome1.txt** you should get 1 line for a sample.

I'm currently working on the next step so i can't help you yet

**Comment by GreeshmaThulasi** [comment]
Thank you very much @dprat , for the explanation.
I did accordingly. One you have done with your complete analysis, please inform :)

Thanks in advance

**Comment by smruti241** [comment]
@dprat  how did you use predictor.py script? I was getting error of index out of range. Can you please explain from profile.py script to training the model? How did you do it?
