### ISSUE TITLE
combProf.sh

### ISSUE THREAD

**Issue by dprat** [rstraver/sanefalcon#4]
Hi Roy, 

We're trying to use sanefalcon with my lab. Though it's been a moment i'm stuck in the last step of the training.
I created all the files requested, but at the end i'm not sure to understand what information we get.
In the read me at part 3.3 Getting nucleosome profiles, you say:

> The following scripts will combine the read start profiles per direction:
> > ./combProf.sh searchDir >> upstreamProfs.csv
> > ./combProfI.sh searchDir >> downstreamProfs.csv
> 
> These scripts will use a built-in find function to detect profile files and merge them per upstream or downstream direction for each sample. At this point, I do not have a seperate script to combine the upstream and downstream profiles. Instead just open them in a spreadsheet tool, sort them both by file name so their orders are aligned and reverse the upstream profile (left most value must become rightmost etc), then stitch the two together by putting the downstream profiles after the upstream profiles. Note there is a value in the middle that has to be removed as both sides also take the nucleosome center base pair into account, thus providing this number twice. You should find the last number from the upstream matches the first number of the downstream profiles when putting them together. Just delete one of the two columns to get rid of this problem, then save the combined profiles in a new file (plain text/csv) for further analysis. The final result should contain the samplename in the first column, then followed by only read start counts per position in every column after that.

Though from the file i get i don't have this
here are my 2 files:

<img width="1673" alt="capture d ecran 2018-06-01 a 17 43 43" src="https://user-images.githubusercontent.com/36034699/40849870-6efe4a44-65c3-11e8-880b-a8dbbc1e35c3.png">

But the end of my upstream file doesn't correspond to the start of my downstream file

i probably made a mistake somewhere ?

Thank you !

**Comment by rstraver** [comment]
Hi, could you e-mail me those 2 files so I can just check what is up with them through some plotting etc?
Please send them here: r.straver-2@umcutrecht.nl
