### ISSUE TITLE
predictor.py

### ISSUE THREAD

**Issue by ruixuechen** [rstraver/sanefalcon#6]
Hi,@rstraver 

when I run the shell script :
python sanefalcon-master/predictor.py trainNuclnew.csv  reference  test_A

the error I got:
- Training stage:
0 samples overlap
375 samples noOverlap
Traceback (most recent call last):
  File "predictor.py", line 511, in <module>
    main()
  File "predictor.py", line 364, in main
    correlations = getCorrelationProfile(samples,reference,trainingSet,yVals)
  File "predictor.py", line 117, in getCorrelationProfile
    for i in range(len(samples[trainingSet[0]])):
IndexError: list index out of range
 
I probably made a mistake somewhere ?

Thanks.

**Comment by rstraver** [comment]
Seeing your e-mail I assume you still would like an anwer:

It looks like the trainingSet list is empty, meaning the  file you provided with answers (reference) for a set of samples (i.e. known fraction for a bunch of male samples) was either empty or showed no overlap with the samples you provided (trainNuclnew.csv). This could be caused by a slight difference in file names or some formatting issues in the reference file.

**Comment by ruixuechen** [comment]
Thank you for your quick reply，
I think there are some problems with my reference file format（reference）.Can you give me an example to tell me the format of the reference file?




This is my trainNuclnew.csv file：



 Look forward to your reply.


------------------ 原始邮件 ------------------
发件人: "Roy Straver"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 下午5:20
收件人: "VUmcCGP/sanefalcon"<sanefalcon@noreply.github.com>;
抄送: "511866357"<511866357@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [VUmcCGP/sanefalcon] predictor.py (#6)




Seeing your e-mail I assume you still would like an anwer:
 
It looks like the trainingSet list is empty, meaning the  file you provided with answers (reference) for a set of samples (i.e. known fraction for a bunch of male samples) was either empty or showed no overlap with the samples you provided (trainNuclnew.csv). This could be caused by a slight difference in file names or some formatting issues in the reference file.

**Comment by rstraver** [comment]
I think something went wrong as I can't see your file (be aware the e-mail goes through github).

However, it's a bit hard for me to figure it out right now (been a while and it seems my own documentation is a little lacking here). Based on the loading function (loadRefFile) I'd expect something like:
> samplename fraction sex

i.e.:
> sample1 0.12 Male
> sample2 0.10 Male
> sample3 0.02 Female

Anyway, in the output you sent before:
> 0 samples overlap

that 0 should be the number of training samples you provided (Male) if everthing goes well, so if you try editing your reference file you can use that as in indicator of things were fixed.
