### ISSUE TITLE
Negative fetal fractions

### ISSUE THREAD

**Issue by natalia0000** [rstraver/sanefalcon#8]
Hello!
Maybe you came across this problem earlier and you can tell me a solution. On the test data the model produces negative fetal fraction. Maybe I make a mistake when preparing test data?
Boxplots are shown in the picture. Since I train on male pregnancy, apparently for female model just took the distribution as well. All test samples were recorder as femele pregnancy since they did not have reference.
<img width="548" alt="Снимок" src="https://user-images.githubusercontent.com/43029468/82450997-14af9c80-9ab6-11ea-9128-8cd7aba86790.PNG">

**Comment by rstraver** [comment]
I cannot really come up with a logical reason for this other than just some form of data (intake) mistake. Training on pregnancy samples where the fetus is male should work fine and be applicable to pregnancies for a female fetus too. 

Perhaps the dataset has some quirks, like different machines/runs between the training and test sets too, a too small training set to train on, or incorrect folding (i.e. leaving x samples out, determine nucleosome pattern, determine profile for left out samples, repeat for next batch)?
